### ISSUE TITLE
Error in Step 01 - Generate bounding boxes ./run_test.sh

### ISSUE THREAD

**Issue by OmarElzaafaranyBrightskies** [ucbdrive/3d-vehicle-tracking#13]
Traceback (most recent call last):
  File "test_net.py", line 30, in <module>
    from model.utils.net_utils import save_net, load_net, vis_detections
  File "/content/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/utils/net_utils.py", line 7, in <module>
    from model.roi_crop.functions.roi_crop import RoICropFunction
  File "/content/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/roi_crop/functions/roi_crop.py", line 3, in <module>
    from .._ext import roi_crop
  File "/content/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/roi_crop/_ext/roi_crop/__init__.py", line 3, in <module>
    from ._roi_crop import lib as _lib, ffi as _ffi
ImportError: /content/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/roi_crop/_ext/roi_crop/_roi_crop.so: undefined symbol: __cudaPopCallConfiguration

root : 200_14_18895 Finish!
Copy output pkl file to dataset folder...
cp: cannot stat 'vis/faster_rcnn_200_14_18895/detections_val.pkl': No such file or directory
Done!!

**Comment by eborboihuc** [comment]
This is the same issue as #12. Please follow the issue there. I'll just close it.
