### ISSUE TITLE
The output of run_test.sh

### ISSUE THREAD

**Issue by leeyun0414** [ucbdrive/3d-vehicle-tracking#15]
Hello, I have followed the **Quick Start** until **Execution-# Step 01 - Generate bounding boxes**.
I skipped the **# Step 00 (Optional) - Training on GTA dataset** part, then run ```./run_test.sh```, It gave me the output like : 
```
Called with args:
Namespace(anno='val', cfg_file='cfgs/res101.yml', checkepoch=14, checkpoint=18895, checksession=200, class_agnostic=False, cuda=True, dataset='gta_det', imdb_name='gta_det_train', imdbval_name='gta_det_val', large_scale=False, load_dir='models', mGPUs=False, net='res101', parallel_type=0, set_cfgs=['ANCHOR_SCALES', '[2, 4, 8, 16]', 'ANCHOR_RATIOS', '[0.5,1,2]', 'MAX_NUM_GT_BOXES', '100'], vis=True)
Loaded dataset `gta_det_val` for training
Set proposal method: gt
Preparing training data...
done
0 roidb entries
load checkpoint models/res101/gta_det/faster_rcnn_200_14_18895.pth
load model successfully!
Evaluating detections
test time: 0.0008s

my_pc : 200_14_18895 Finish!
Copy output pkl file to dataset folder...
Done!!
```
I have no idea how to show the output of detection? I think the problem might be the nothing input, could someone give me help?

If this problem fixed, what's the next step i should to do to see the output?
Thanks!

**Comment by leeyun0414** [comment]
After I unzip the data to ```/gta5_tracking/val/image/```, it could show up something, but it has out of memory problem.
```
...
...
       [  936.85046023,   566.48631052],
       [  862.41001604,   560.96226032],
       [-2334.6868131 ,   396.96692857],
       [  483.410594  ,   565.48375872],
       [  836.96308186,   553.4352448 ],
       [  957.1582513 ,   559.52538534],
       [  942.17562782,   544.27242047]]), 'img_id': 4692, 'image': 'data/gta5_tracking/val/image/rec_10262031_snow_8h23m_x-681y-1358tox2424y-242/1540611218629_final.jpg', 'max_classes': array([1, 1, 1, 1, 1, 1, 1, 1, 1]), 'max_overlaps': array([1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32), 'need_crop': 0}]
[1.77777778 1.77777778 1.77777778 ... 1.77777778 1.77777778 1.77777778]
[   0 3132 3131 ... 1558 1574 4692]
4693 roidb entries
models/res101/gta_det
load checkpoint models/res101/gta_det/faster_rcnn_200_14_18895.pth
load model successfully!
Traceback (most recent call last):020s   
  File "test_net.py", line 304, in <module>
    num_boxes, fixed_center)
  File "/home/ee904-pc4/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ee904-pc4/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/faster_rcnn/faster_rcnn.py", line 46, in forward
    base_feat = self.RCNN_base(im_data)
  File "/home/ee904-pc4/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ee904-pc4/.local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/ee904-pc4/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ee904-pc4/.local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/ee904-pc4/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ee904-pc4/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/faster_rcnn/resnet.py", line 95, in forward
    out = self.bn3(out)
  File "/home/ee904-pc4/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ee904-pc4/.local/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 66, in forward
    exponential_average_factor, self.eps)
  File "/home/ee904-pc4/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 1254, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA error: out of memory

ee904-pc4 : 200_14_18895 Finish!
Copy output pkl file to dataset folder...
Done!!
```
Is there any way to solve it ?

**Comment by leeyun0414** [comment]
After I unzip the files to ```gta5_tracking/val/label/``` and ```gta5_tracking/val/image/```, this problem solved.
