### ISSUE TITLE
AssertionError: ERROR: length of GT frames 4741 not equals detected ones 46250

### ISSUE THREAD

**Issue by LOGIC-10** [ucbdrive/3d-vehicle-tracking#52]

**Comment by LOGIC-10** [comment]
what dose that mean?

Traceback (most recent call last):
  File "loader/gen_pred.py", line 193, in <module>
    main()
  File "loader/gen_pred.py", line 188, in main
    ds = Dataset()
  File "loader/gen_pred.py", line 114, in __init__
    len(self.data_path), self.det_result.shape[0])
AssertionError: ERROR: length of GT frames 4741 not equals detected ones 46250
